In [1]:
import numpy as np
import time

In [3]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.13817166 0.67723353 0.6701984  0.18791172], a shape = (4,), a data type = float64


In [4]:
#Numpy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);         print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);      print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.3359408  0.1028022  0.17839699 0.12673165], a shape = (4,), a data type = float64


In [5]:
# Nunmpy routines which allocate memory and fill with user specifies values
a = np.array([5,4,3,2]);   print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]);  print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [8]:
a = np.arange(10)
print(a)

try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
The error message you'll see is
index 10 is out of bounds for axis 0 with size 10


In [9]:
a[2:7:2]

array([2, 4, 6])

In [10]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a[:3]

array([0, 1, 2])

### Single Vector operations


In [12]:
a = np.array([1,2,3,4])
print(a)

b = -a
print(b)

b = np.sum(a)
print(b)

b = np.mean(a)
print(b)

b = a**2
print(b)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


### Vector Vector element wise

In [13]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(a+b)

[0 0 6 8]


In [14]:
c = np.array([1,2])
try:
    d = a +c 
except Exception as e:
    print("The error message you'll see is")
    print(e)

The error message you'll see is
operands could not be broadcast together with shapes (4,) (2,) 


### Scaler Vector Operations


In [15]:
a = np.array([1,2,3,4])
b = a*5
print(b)

[ 5 10 15 20]


### Vector Vector Dot Product

In [18]:
def my_dot(a,b):
    x = 0
    for i in range(len(a)):
        x = x + a[i]*b[i]
    return x
    
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(my_dot(a,b))

24


In [19]:
c = np.dot(a,b)
print(c)

24


In [21]:
d = np.dot(b,a)
print(d)

24


In [22]:
# to calculate the differnce in time
# Using the inbuilt dot function

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print(f"The vectorized operations took time : {1000*(toc-tic)}")

tic = time.time()
c = my_dot(a,b)
toc = time.time()
print(c)
print(f"loop version took time : {1000*(toc-tic)}")

24
The vectorized operations took time : 0.09989738464355469
24
loop version took time : 0.14662742614746094


### Matrix Creation

In [23]:
a = np.zeros((1,5))
print(a)

[[0. 0. 0. 0. 0.]]


In [24]:
a = np.random.random_sample((1,1))
print(a)

[[0.43363154]]


In [25]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [26]:


#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")



a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
